### ISSUE TITLE
Can I send USDT to this wallet ?

### ISSUE THREAD

**Issue by congnghiakhiem** [OmniLayer/omnicore-lite-deprecated#3]
Hi,

Can I send TetherUS(USDT) (or other OMNI tokens) to this wallet ?

Thanks,

**Comment by Noah-svg** [comment]
害  现在一般交易所都是接入优盾钱包了，开放的api接口，一键接入实现数字资产的快捷充提，支持btc、eth、usdt等100+币种，实现钱包创建、业务接入、地址生成、充币提币、交易查询、资金归集等功能，老好用了
